### ISSUE TITLE
embed error

### ISSUE THREAD

**Issue by dongsu8142** [ansonfoong/Katana#8]
error: TS2740 [ERROR]: Type '{ title: string; }' is missing the following properties from type 'MessageEmbed': getTitle, setTitle, getType, setType, and 20 more.
      embed: { title: 'hello' }

**Comment by dongsu8142** [comment]
example I get this error

**Comment by stuyy** [comment]
Could you provide the code that you worked with? Was it just from the example?

**Comment by dongsu8142** [comment]
yes example

**Comment by stuyy** [comment]
Got it. Just tried it now and it seems to be an error where it was type checking with a Message Embed class. Will fix this soon. For now you can just create a MessageEmbed the same way you would in Discord.JS v12.

**Comment by dongsu8142** [comment]
Please change it quickly.

**Comment by stuyy** [comment]
I've updated the README.md example, for the time being please use MessageEmbed class to send embeds. Thank you for raising this issue.
