### ISSUE TITLE
DM message errer

### ISSUE THREAD

**Issue by dongsu8142** [ansonfoong/Katana#9]
error: Uncaught TypeError: Cannot read property 'get' of undefined
  const member = guild.members.get(author.id);
                               ^
    at buildMessage (https://deno.land/x/katana/src/utils/resolvers.ts:259:32)
    at async default (https://deno.land/x/katana/src/handlers/MESSAGE_CREATE.ts:8:19)

**Comment by stuyy** [comment]
DM Channels are not yet supported, only Text & Guild channels ATM, will need to work on DM channels later.

**Comment by dongsu8142** [comment]
Thank you.

**Comment by stuyy** [comment]
I had just added support for DMs. It's a bit buggy (if the bot sends a number of messages it'll throw an error where the author is undefined.
